apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aap-opa

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: opa-policies
    files:
      - policies/aap/examples/allowed_false.rego
      - policies/aap/examples/extra_vars_allowlist.rego
      - policies/aap/examples/extra_vars_validation.rego
      - policies/aap/examples/github_repo_validation.rego
      - policies/aap/examples/global_credential_allowed_false.rego
      - policies/aap/examples/jt_naming_validation.rego
      - policies/aap/examples/maintenance_window.rego
      - policies/aap/examples/mismatch_prefix_allowed_false.rego
      - policies/aap/examples/project_scm_branch.rego
      - policies/aap/examples/restrict_inv_use_to_org.rego
      - policies/aap/examples/superuser_allowed_false.rego
      - policies/aap/examples/team_based_extra_vars_restriction.rego
